2025-02-26 17:00:49,422 INFO: Supabase registration response: user=User(id='82d8f66b-bc6a-42ac-bbdc-0b05d872a654', app_metadata={'provider': 'email', 'providers': ['email']}, user_metadata={'email': 'd03angelv@gmail.com', 'email_verified': False, 'phone_verified': False, 'sub': '82d8f66b-bc6a-42ac-bbdc-0b05d872a654'}, aud='authenticated', confirmation_sent_at=datetime.datetime(2025, 2, 26, 22, 0, 48, 196482, tzinfo=TzInfo(UTC)), recovery_sent_at=None, email_change_sent_at=None, new_email=None, new_phone=None, invited_at=None, action_link=None, email='d03angelv@gmail.com', phone='', created_at=datetime.datetime(2025, 2, 26, 21, 57, 40, 930320, tzinfo=TzInfo(UTC)), confirmed_at=None, email_confirmed_at=None, phone_confirmed_at=None, last_sign_in_at=None, role='authenticated', updated_at=datetime.datetime(2025, 2, 26, 22, 0, 49, 391310, tzinfo=TzInfo(UTC)), identities=[UserIdentity(id='82d8f66b-bc6a-42ac-bbdc-0b05d872a654', identity_id='4a5fc793-8508-4d2a-8063-f0fbf67152b8', user_id='82d8f66b-bc6a-42ac-bbdc-0b05d872a654', identity_data={'email': 'd03angelv@gmail.com', 'email_verified': False, 'phone_verified': False, 'sub': '82d8f66b-bc6a-42ac-bbdc-0b05d872a654'}, provider='email', created_at=datetime.datetime(2025, 2, 26, 21, 57, 40, 934629, tzinfo=TzInfo(UTC)), last_sign_in_at=datetime.datetime(2025, 2, 26, 21, 57, 40, 934585, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2025, 2, 26, 21, 57, 40, 934629, tzinfo=TzInfo(UTC)))], is_anonymous=False, factors=None) session=None [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:73]
2025-02-26 17:00:51,359 ERROR: Registration error for d03angelv@gmail.com: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "users_email_key"
DETAIL:  Key (email)=(d03angelv@gmail.com) already exists.

[SQL: INSERT INTO users (id, email, password_hash, created_at) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(created_at)s)]
[parameters: {'id': '82d8f66b-bc6a-42ac-bbdc-0b05d872a654', 'email': 'd03angelv@gmail.com', 'password_hash': None, 'created_at': datetime.datetime(2025, 2, 26, 22, 0, 51, 76175)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:94]
2025-02-26 17:02:09,993 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 17:06:09,779 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 17:06:10,507 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 17:07:16,001 INFO: Attempting to register user: barackemegan@gmail.com [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:71]
2025-02-26 17:07:17,682 INFO: Supabase registration response: user=User(id='21a18502-b273-4817-91b0-bbfd5c4dc291', app_metadata={'provider': 'email', 'providers': ['email']}, user_metadata={'email': 'barackemegan@gmail.com', 'email_verified': False, 'phone_verified': False, 'sub': '21a18502-b273-4817-91b0-bbfd5c4dc291'}, aud='authenticated', confirmation_sent_at=datetime.datetime(2025, 2, 26, 22, 7, 16, 438690, tzinfo=TzInfo(UTC)), recovery_sent_at=None, email_change_sent_at=None, new_email=None, new_phone=None, invited_at=None, action_link=None, email='barackemegan@gmail.com', phone='', created_at=datetime.datetime(2025, 2, 26, 22, 7, 16, 427395, tzinfo=TzInfo(UTC)), confirmed_at=None, email_confirmed_at=None, phone_confirmed_at=None, last_sign_in_at=None, role='authenticated', updated_at=datetime.datetime(2025, 2, 26, 22, 7, 17, 611576, tzinfo=TzInfo(UTC)), identities=[UserIdentity(id='21a18502-b273-4817-91b0-bbfd5c4dc291', identity_id='714509c0-f8aa-4cd8-912d-f973e15333b3', user_id='21a18502-b273-4817-91b0-bbfd5c4dc291', identity_data={'email': 'barackemegan@gmail.com', 'email_verified': False, 'phone_verified': False, 'sub': '21a18502-b273-4817-91b0-bbfd5c4dc291'}, provider='email', created_at=datetime.datetime(2025, 2, 26, 22, 7, 16, 432839, tzinfo=TzInfo(UTC)), last_sign_in_at=datetime.datetime(2025, 2, 26, 22, 7, 16, 432791, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2025, 2, 26, 22, 7, 16, 432839, tzinfo=TzInfo(UTC)))], is_anonymous=False, factors=None) session=None [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:79]
2025-02-26 17:07:17,868 INFO: Successfully created local user record for barackemegan@gmail.com [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:92]
2025-02-26 17:09:04,188 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 17:09:12,717 WARNING: Supabase logout failed for user barackemegan@gmail.com: 'SUPABASE_ANON_KEY' [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:174]
2025-02-26 17:09:12,719 INFO: User barackemegan@gmail.com logged out successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:177]
2025-02-26 17:09:23,310 INFO: User Vincent.dangelo@gilmour.org logged in successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:41]
2025-02-26 17:09:41,495 INFO: Deleted user barackemegan@gmail.com from Supabase [in /Users/d_angel/Access_Point_V3/app/routes/admin.py:129]
2025-02-26 17:09:47,237 ERROR: Failed to delete user from Supabase: User not found [in /Users/d_angel/Access_Point_V3/app/routes/admin.py:131]
2025-02-26 17:09:51,379 WARNING: Supabase logout failed for user Vincent.dangelo@gilmour.org: 'SUPABASE_ANON_KEY' [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:174]
2025-02-26 17:09:51,380 INFO: User Vincent.dangelo@gilmour.org logged out successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:177]
2025-02-26 17:10:03,486 ERROR: Login error for user barackemegan@gmail.com: Invalid login credentials [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:50]
2025-02-26 17:10:14,126 INFO: Attempting to register user: barackemegan@gmail.com [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:71]
2025-02-26 17:10:15,650 INFO: Supabase registration response: user=User(id='d6d17d05-06d6-4fa0-bae3-814a1a3542af', app_metadata={'provider': 'email', 'providers': ['email']}, user_metadata={'email': 'barackemegan@gmail.com', 'email_verified': False, 'phone_verified': False, 'sub': 'd6d17d05-06d6-4fa0-bae3-814a1a3542af'}, aud='authenticated', confirmation_sent_at=datetime.datetime(2025, 2, 26, 22, 10, 14, 384898, tzinfo=TzInfo(UTC)), recovery_sent_at=None, email_change_sent_at=None, new_email=None, new_phone=None, invited_at=None, action_link=None, email='barackemegan@gmail.com', phone='', created_at=datetime.datetime(2025, 2, 26, 22, 10, 14, 379181, tzinfo=TzInfo(UTC)), confirmed_at=None, email_confirmed_at=None, phone_confirmed_at=None, last_sign_in_at=None, role='authenticated', updated_at=datetime.datetime(2025, 2, 26, 22, 10, 15, 566982, tzinfo=TzInfo(UTC)), identities=[UserIdentity(id='d6d17d05-06d6-4fa0-bae3-814a1a3542af', identity_id='1f5bc947-e49b-4fb0-9827-2e298fdbb6fe', user_id='d6d17d05-06d6-4fa0-bae3-814a1a3542af', identity_data={'email': 'barackemegan@gmail.com', 'email_verified': False, 'phone_verified': False, 'sub': 'd6d17d05-06d6-4fa0-bae3-814a1a3542af'}, provider='email', created_at=datetime.datetime(2025, 2, 26, 22, 10, 14, 382181, tzinfo=TzInfo(UTC)), last_sign_in_at=datetime.datetime(2025, 2, 26, 22, 10, 14, 382138, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2025, 2, 26, 22, 10, 14, 382181, tzinfo=TzInfo(UTC)))], is_anonymous=False, factors=None) session=None [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:79]
2025-02-26 17:10:15,878 INFO: Successfully created local user record for barackemegan@gmail.com [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:92]
2025-02-26 17:39:24,030 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 17:39:24,405 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 17:41:07,716 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 17:41:10,411 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:42:29,092 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:42:29,232 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:42:29,232 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:42:48,103 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:42:48,450 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:43:02,891 WARNING: Supabase logout failed for user barackemegan@gmail.com: 'SUPABASE_ANON_KEY' [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:174]
2025-02-26 17:43:02,892 INFO: User barackemegan@gmail.com logged out successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:177]
2025-02-26 17:43:11,285 INFO: User Vincent.dangelo@gilmour.org logged in successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:41]
2025-02-26 17:50:29,366 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:52:35,103 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:52:47,796 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:52:49,498 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:53:23,599 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:54:17,009 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:54:23,589 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:54:40,444 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:54:45,934 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:54:49,443 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
2025-02-26 17:55:10,584 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:26]
